"""Briefing batch collection — polling, parsing, and writing briefing JSONs.

Extracted from retrieve_batch_briefings.py.

This module handles the *briefings* batch pipeline, which uses kitai.batch
(not the OpenAI client directly). For the sector batch pipeline see
pipeline.batch_collect which uses the OpenAI client API directly.

custom_id convention: "briefing-YYYY-MM-DD-{topic_id[:8]}"

Exit-code contract (preserved from source script):
    sys.exit(1) — hard failure (sentinel missing, batch failed/expired)
    sys.exit(2) — batch still in flight; caller should retry later

Deduplication note:
    read_pending_batch_id() from pipeline.batch_collect is NOT re-defined here.
    Callers should use:
        from pipeline.batch_collect import read_pending_batch_id
        batch_id = read_pending_batch_id(PENDING_BRIEFINGS_BATCH_FILE)

Dependency note:
    collect_briefing_results() calls daily_briefing._sector_crosscheck, which
    is a private function in the project-level daily_briefing.py module.
    This import works when the project root is on sys.path (default when running
    from the project directory).
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path

from openai import OpenAI

from daily_briefing import _sector_crosscheck  # project-level dependency
from kitai.batch import check_batch_job, download_batch_results

# ── Constants ──────────────────────────────────────────────────────────────────

_TERMINAL_STATES: frozenset[str] = frozenset({"completed", "failed", "expired", "cancelled"})


# ── Sentinel reading ────────────────────────────────────────────────────────────


def read_spike_metadata(metadata_file: Path) -> dict:
    """Load the sidecar metadata file written by create_batch_briefings.py.

    Returns {custom_id: {date, topic_id, label, spike_ratio, article_count, sources}}.

    Args:
        metadata_file: Path to pending_briefings_meta.json.

    NOTE: calls sys.exit(1) if the metadata file is absent.
    """
    if not metadata_file.exists():
        print(  # NOTE: uses print()
            f"[error] Metadata sidecar not found at {metadata_file}.\n"
            "Re-run create_batch_briefings.py to regenerate it."
        )
        sys.exit(1)  # NOTE: uses sys.exit(1) — metadata file missing
    return json.loads(metadata_file.read_text(encoding="utf-8"))


# ── Batch status ────────────────────────────────────────────────────────────────


def check_briefings_batch_status(client: OpenAI, batch_id: str) -> None:
    """Check briefings batch status via kitai.batch.check_batch_job.

    Args:
        client:   Authenticated OpenAI client instance.
        batch_id: The batch job ID.

    NOTE: calls sys.exit(2) if batch is still in progress (retry is safe).
    NOTE: calls sys.exit(1) if batch failed, expired, or was cancelled.
    """
    status = check_batch_job(client, batch_id)
    counts = status.get("request_counts", {})

    print(  # NOTE: uses print()
        f"Batch {batch_id} -> status: {status['status']} | "
        f"completed: {counts.get('completed', '?')} | "
        f"failed: {counts.get('failed', '?')}"
    )

    if status["status"] not in _TERMINAL_STATES:
        print("Batch is still in progress. Re-run this script once it completes.")  # NOTE: uses print()
        sys.exit(2)  # NOTE: uses sys.exit(2) — not ready; retry is safe

    if status["status"] != "completed":
        print(  # NOTE: uses print()
            f"[error] Batch ended with status '{status['status']}'. "
            "No results to collect. Check the OpenAI dashboard for details."
        )
        sys.exit(1)  # NOTE: uses sys.exit(1) — batch failed/expired/cancelled


# ── Parsing ────────────────────────────────────────────────────────────────────


def parse_briefing_custom_id(custom_id: str) -> tuple[str, str] | None:
    """Extract (date, topic_id_prefix) from 'briefing-YYYY-MM-DD-{tid[:8]}'.

    Returns None if the format does not match (defensive guard — should not
    happen with tasks generated by create_batch_briefings.py).
    """
    parts = custom_id.split("-", maxsplit=2)
    # Expected: ["briefing", "YYYY", "MM-DD-{tid[:8]}"]
    if len(parts) != 3 or parts[0] != "briefing":
        return None
    rest = parts[2]  # "MM-DD-xxxxxxxx"
    dash_pos = rest.rfind("-")
    if dash_pos == -1:
        return None
    date_str = f"{parts[1]}-{rest[:dash_pos]}"   # "YYYY-MM-DD"
    tid_prefix = rest[dash_pos + 1:]              # "xxxxxxxx" (first 8 chars of UUID)
    return date_str, tid_prefix


def collect_briefing_results(
    items:    list[dict],
    metadata: dict,
) -> tuple[dict[str, list[dict]], int, int]:
    """Parse batch results and group assembled spikes by date.

    For each item:
      - Extracts LLM answer from the response body
      - Looks up pre-retrieved sources from the sidecar metadata
      - Runs sector cross-check locally via daily_briefing._sector_crosscheck
      - Groups into {date: [spike_dict, ...]}

    Args:
        items:    Parsed batch items from kitai.batch.download_batch_results().
        metadata: Sidecar dict from read_spike_metadata().

    Returns:
        (spikes_by_date, ok_count, failed_count)
        spikes_by_date: {date_str: [assembled spike dict]}
        ok_count:       items successfully parsed
        failed_count:   items with errors or parse failures

    Dependency: calls daily_briefing._sector_crosscheck(label) — a project-level
    function that queries sector data locally without any API calls.
    """
    spikes_by_date: dict[str, list[dict]] = defaultdict(list)
    ok_count    = 0
    failed_count = 0

    for item in items:
        custom_id = item.get("custom_id", "unknown")

        meta = metadata.get(custom_id)
        if meta is None:
            print(f"[warn] No metadata for custom_id '{custom_id}' — skipping.")  # NOTE: uses print()
            failed_count += 1
            continue

        date_str = meta["date"]

        if item.get("error"):
            print(f"[fail] {date_str}/{meta['label']!r}: batch item error -> {item['error']}")  # NOTE: uses print()
            failed_count += 1
            continue

        response = item.get("response")
        if response is None or response.get("status_code") != 200:
            code = response.get("status_code") if response else "null"
            print(f"[fail] {date_str}/{meta['label']!r}: HTTP {code}")  # NOTE: uses print()
            failed_count += 1
            continue

        try:
            answer = response["body"]["choices"][0]["message"]["content"]
        except (KeyError, IndexError) as exc:
            print(  # NOTE: uses print()
                f"[fail] {date_str}/{meta['label']!r}: unexpected response structure -> {exc}"
            )
            failed_count += 1
            continue

        # Sector cross-check — local, no API call
        sectors = _sector_crosscheck(meta["label"])

        spikes_by_date[date_str].append({
            "topic_id":      meta["topic_id"],
            "label":         meta["label"],
            "spike_ratio":   meta["spike_ratio"],
            "article_count": meta["article_count"],
            "rag_answer":    answer,
            "rag_sources":   meta["sources"][:4],  # cap at 4 like daily_briefing.py
            "sectors":       sectors,
        })
        print(f"[ok]   {date_str} / {meta['label']!r}")  # NOTE: uses print()
        ok_count += 1

    return dict(spikes_by_date), ok_count, failed_count


# ── Writing briefing JSONs ─────────────────────────────────────────────────────


def save_briefings(
    spikes_by_date: dict[str, list[dict]],
    briefings_dir: Path,
) -> int:
    """Write data/briefings/{date}.json for each date in spikes_by_date.

    If a briefing JSON already exists for a date (e.g. from a partial run),
    it is overwritten with the freshly collected spikes.

    Args:
        spikes_by_date: {date_str: [spike_dict, ...]} from collect_briefing_results().
        briefings_dir:  Directory where briefing JSONs are written.

    Returns:
        Number of files written.

    Output file schema:
        {
            "date": "YYYY-MM-DD",
            "n_spikes": N,
            "spikes": [{ topic_id, label, spike_ratio, article_count,
                         rag_answer, rag_sources, sectors }, ...]
        }
    """
    briefings_dir.mkdir(parents=True, exist_ok=True)
    written = 0

    for date_str, spikes in sorted(spikes_by_date.items()):
        briefing = {
            "date":     date_str,
            "n_spikes": len(spikes),
            "spikes":   spikes,
        }
        out_path = briefings_dir / f"{date_str}.json"
        out_path.write_text(json.dumps(briefing, indent=2, default=str), encoding="utf-8")
        print(f"  Wrote {out_path}  ({len(spikes)} spike(s))")  # NOTE: uses print()
        written += 1

    return written
