"""Sentiment visualization utilities.

Extracted from visualize_sentiment.py.

Module-level path constants (INPUT_FILE, CHARTS_DIR) have been replaced
with explicit parameters so callers can inject their own paths.

Invariants:
  - All three chart functions are independent — a failure in one does not
    affect the others; call them individually.
  - load_sentiment_data must be called before the chart functions.
  - "No data to plot" warns are expected for infrequent sectors with fewer
    than MIN_DATA_POINTS entries.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# ── Constants ──────────────────────────────────────────────────────────────────

SENTIMENT_SCORE: dict[str, int] = {"positive": 1, "neutral": 0, "negative": -1}

SENTIMENT_COLORS: dict[str, str] = {
    "positive": "#27ae60",
    "neutral": "#95a5a6",
    "negative": "#c0392b",
}

ROLLING_WINDOW = 5    # trading days for rolling average in trend chart
MIN_DATA_POINTS = 3   # sectors with fewer points are excluded from trend chart


# ── Data loading ────────────────────────────────────────────────────────────────


def load_sentiment_data(input_file: Path) -> pd.DataFrame:
    """Load a sector_summary TSV and add a numeric sentiment_score column.

    Args:
        input_file: Path to sector_summary.tsv (generated by read_sector_results.py).

    Returns:
        DataFrame with columns: date, sector, sentiment, sentiment_score, ...
        Rows with null sentiment_score, date, or sector are dropped.
        Sorted by date.

    NOTE: calls sys.exit(1) if input_file does not exist.
    """
    if not input_file.exists():
        print(f"[error] Input file not found: {input_file}")  # NOTE: uses print()
        print("Run read_sector_results.py first to generate it.")  # NOTE: uses print()
        sys.exit(1)  # NOTE: uses sys.exit(1) — missing input file

    df = pd.read_csv(input_file, sep="\t", parse_dates=["date"])
    df["sentiment_score"] = df["sentiment"].map(SENTIMENT_SCORE)
    df = df.dropna(subset=["sentiment_score", "date", "sector"])
    df = df.sort_values("date").reset_index(drop=True)

    print(  # NOTE: uses print()
        f"Loaded {len(df)} rows | "
        f"{df['date'].nunique()} date(s) | "
        f"{df['sector'].nunique()} sector(s)"
    )
    return df


# ── Chart 1: Heatmap ────────────────────────────────────────────────────────────


def chart_heatmap(df: pd.DataFrame, charts_dir: Path) -> None:
    """Save a weekly heatmap of mean sentiment score (sector Y × week X).

    Weekly aggregation smooths daily noise and keeps the chart readable
    for long date ranges.
    Color scale: red (-1 negative) -> white (0 neutral) -> green (+1 positive).

    Output: charts_dir/sentiment_heatmap.png

    Args:
        df:         DataFrame from load_sentiment_data().
        charts_dir: Directory where the PNG is written.
    """
    df_w = df.copy()
    df_w["week"] = df["date"].dt.to_period("W").dt.start_time

    pivot = (
        df_w.groupby(["week", "sector"])["sentiment_score"]
        .mean()
        .unstack("sector")
    )

    if pivot.empty:
        print("[warn] heatmap: no data to plot.")  # NOTE: uses print()
        return

    fig_w = max(12, len(pivot) * 0.45)
    fig_h = max(5, len(pivot.columns) * 0.45)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))

    sns.heatmap(
        pivot.T,
        ax=ax,
        cmap="RdYlGn",
        vmin=-1, vmax=1, center=0,
        linewidths=0.4,
        linecolor="#e0e0e0",
        cbar_kws={
            "label": "Sentiment score  (-1 neg -> 0 neutral -> +1 pos)",
            "shrink": 0.6,
        },
    )

    # Format x-axis tick labels as "Mon 'YY"
    week_labels = [w.strftime("%b '%y") for w in pivot.index]
    ax.set_xticklabels(week_labels, rotation=45, ha="right", fontsize=8)
    ax.set_yticklabels(ax.get_yticklabels(), rotation=0, fontsize=9)
    ax.set_title("Sector Sentiment - Weekly Heatmap", fontsize=14, fontweight="bold", pad=12)
    ax.set_xlabel("")
    ax.set_ylabel("")

    plt.tight_layout()
    out = charts_dir / "sentiment_heatmap.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved -> {out}")  # NOTE: uses print()


# ── Chart 2: Trend lines ────────────────────────────────────────────────────────


def chart_trends(df: pd.DataFrame, charts_dir: Path) -> None:
    """Save a small-multiples rolling-sentiment line chart per sector.

    Each subplot shows one sector. The shaded area above zero is green
    (positive periods) and below zero is red (negative periods), making
    regime shifts immediately visible.

    Sectors with fewer than MIN_DATA_POINTS data points are excluded.

    Output: charts_dir/sentiment_trends.png

    Args:
        df:         DataFrame from load_sentiment_data().
        charts_dir: Directory where the PNG is written.
    """
    daily = (
        df.groupby(["date", "sector"])["sentiment_score"]
        .mean()
        .unstack("sector")
        .sort_index()
    )

    valid = [c for c in daily.columns if daily[c].notna().sum() >= MIN_DATA_POINTS]
    if not valid:
        print("[warn] trends: no sectors with enough data points.")  # NOTE: uses print()
        return

    daily = daily[valid]
    smoothed = daily.rolling(window=ROLLING_WINDOW, min_periods=1, center=True).mean()

    ncols = 3
    nrows = (len(valid) + ncols - 1) // ncols
    fig, axes = plt.subplots(
        nrows, ncols,
        figsize=(18, nrows * 3.2),
        sharex=True,
        squeeze=False,
    )

    for i, sector in enumerate(sorted(valid)):
        ax = axes[i // ncols][i % ncols]
        series = smoothed[sector].dropna()

        ax.axhline(0, color="#cccccc", linewidth=0.8, zorder=1)
        ax.fill_between(
            series.index, series, 0,
            where=(series >= 0), color=SENTIMENT_COLORS["positive"], alpha=0.3,
        )
        ax.fill_between(
            series.index, series, 0,
            where=(series < 0), color=SENTIMENT_COLORS["negative"], alpha=0.3,
        )
        ax.plot(series.index, series, color="#2c3e50", linewidth=1.2, zorder=2)

        ax.set_title(sector, fontsize=9, fontweight="bold")
        ax.set_ylim(-1.2, 1.2)
        ax.set_yticks([-1, 0, 1])
        ax.set_yticklabels(["neg", "0", "pos"], fontsize=7)
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%b '%y"))
        ax.tick_params(axis="x", rotation=45, labelsize=7)

    # Hide unused subplot cells
    for j in range(len(valid), nrows * ncols):
        axes[j // ncols][j % ncols].set_visible(False)

    fig.suptitle(
        f"Sector Sentiment Trends  ({ROLLING_WINDOW}-day rolling average)",
        fontsize=14, fontweight="bold", y=1.01,
    )
    plt.tight_layout()
    out = charts_dir / "sentiment_trends.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved -> {out}")  # NOTE: uses print()


# ── Chart 3: Distribution ───────────────────────────────────────────────────────


def chart_distribution(df: pd.DataFrame, charts_dir: Path) -> None:
    """Save a stacked horizontal bar chart of % positive / neutral / negative per sector.

    Normalising to 100% makes sectors with different news volumes comparable.
    Sectors are sorted by positive share (highest at top) to create a natural
    ranking of sector sentiment.

    Output: charts_dir/sentiment_distribution.png

    Args:
        df:         DataFrame from load_sentiment_data().
        charts_dir: Directory where the PNG is written.
    """
    counts = (
        df.groupby(["sector", "sentiment"])
        .size()
        .unstack("sentiment")
        .fillna(0)
    )

    # Ensure all three columns exist even if a sentiment value never appeared
    for col in ["positive", "neutral", "negative"]:
        if col not in counts.columns:
            counts[col] = 0.0

    proportions = counts.div(counts.sum(axis=1), axis=0) * 100
    proportions = (
        proportions[["positive", "neutral", "negative"]]
        .sort_values("positive", ascending=True)  # best sector at top
    )

    if proportions.empty:
        print("[warn] distribution: no data to plot.")  # NOTE: uses print()
        return

    fig, ax = plt.subplots(figsize=(10, max(5, len(proportions) * 0.55)))

    left = pd.Series(0.0, index=proportions.index)
    for col, color in SENTIMENT_COLORS.items():
        ax.barh(
            proportions.index,
            proportions[col],
            left=left,
            color=color,
            label=col.capitalize(),
            height=0.65,
        )
        left = left + proportions[col]

    ax.set_xlim(0, 100)
    ax.axvline(50, color="#888888", linewidth=0.7, linestyle="--", alpha=0.6)
    ax.set_xlabel("Share of news items (%)", fontsize=10)
    ax.set_title(
        "Sentiment Distribution by Sector", fontsize=14, fontweight="bold", pad=12
    )
    ax.legend(loc="lower right", framealpha=0.9, fontsize=9)
    ax.tick_params(axis="y", labelsize=9)

    plt.tight_layout()
    out = charts_dir / "sentiment_distribution.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved -> {out}")  # NOTE: uses print()
