on:
  schedule:
    - cron: '0 */5 * * *'  # every 5 hours
  workflow_dispatch:

jobs:  
  build:  
    runs-on: ubuntu-latest  
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
  
    - name: Run Script  
      run: Rscript download.R # Replace script.R with the name of your R script  
      
    # - name: Run Script delete  
    #  run: Rscript script_del.R # Replace script.R with the name of your R script 

    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "scraping" || echo "No changes to commit"
        git push origin || echo "No changes to commit"-
